spring:
  application:
    name: OrderMicroService
  
  datasource:
    driver-class-name: org.h2.Driver 
    url: jdbc:h2:~/orderservice
    username: sa 
    password: password
 
  h2:
    console:
      enabled: true
    
 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
     
server:
  port: 8082
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7000/eureka
    
    
    
